name: Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Check code formatting
      run: npm run format:check

    - name: Run linter
      run: npm run lint

    - name: Generate Prisma client
      run: npm run prisma:generate

    - name: Run tests
      run: npm run test:coverage
      env:
        NODE_ENV: test
        JWT_ACCESS_SECRET: test_access_secret_for_ci
        JWT_REFRESH_SECRET: test_refresh_secret_for_ci
        JWT_EMAIL_SECRET: test_email_secret_for_ci
        JWT_PASSWORD_RESET_SECRET: test_password_reset_secret_for_ci
        DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./backend/coverage
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false
