name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Build application
      run: npm run build

    # TODO: Fix ngx-lite-form test compatibility and re-enable tests
    # - name: Run tests
    #   run: npm run test -- --watch=false --browsers=ChromeHeadless
    #   env:
    #     CI: true

    # - name: Upload test coverage
    #   uses: codecov/codecov-action@v3
    #   with:
    #     directory: ./frontend/coverage/frontend
    #     flags: frontend
    #     name: frontend-coverage
    #     fail_ci_if_error: false
